@startuml
class Compra {
    + Compra()
    + Compra(id:int, fechaCompra:DateTime, compraItems:IList <CompraItem>, codigoDescuento:string, cliente:ApplicationUser)
    + Compra(fechaCompra:DateTime, compraItems:IList <CompraItem>, codigoDescuento:string, cliente:ApplicationUser)
    + Id : int <<get>> <<set>>
    + PrecioTotal : decimal <<get>> <<set>>
    + CodigoDescuento : string? <<get>> <<set>>
}
class "IList`1"<T> {
}
Compra --> "FechaCompra" DateTime
Compra o-> "CompraItems<CompraItem>" "IList`1"
Compra --> "Cliente" ApplicationUser
@enduml
