@startuml
class Genero {
    + Genero()
    + Genero(id:int, nombre:string)
    + Id : int <<get>> <<set>>
    + Nombre : string <<get>> <<set>>
}
class "IList`1"<T> {
}
Genero o-> "Libros<Libro>" "IList`1"
@enduml
