@startuml
class Libro {
    + Libro()
    + Libro(id:int, genero:Genero, generoId:int, editorial:Editorial, editorialId:int, titulo:string, tipoLibro:string, autor:string, calificacionMedia:int, fechaLanzamiento:DateTime, precioCompra:decimal, precioReposicion:decimal, stock:int, compraItems:IList<CompraItem>, resenaItems:IList<ResenaItem>, subastaItems:IList<SubastaItem>, reposicionItems:IList<ReposicionItem>)
    + Id : int <<get>> <<set>>
    + Titulo : string <<get>> <<set>>
    + TipoLibro : string <<get>> <<set>>
    + Autor : string <<get>> <<set>>
    + CalificacionMedia : int <<get>> <<set>>
    + PrecioCompra : decimal <<get>> <<set>>
    + PrecioReposicion : decimal <<get>> <<set>>
    + Stock : int <<get>> <<set>>
    + GeneroId : int <<get>> <<set>>
    + EditorialId : int <<get>> <<set>>
}
class "IList`1"<T> {
}
Libro --> "FechaLanzamiento" DateTime
Libro --> "Genero" Genero
Libro --> "Editorial" Editorial
Libro o-> "CompraItems<CompraItem>" "IList`1"
Libro --> "ResenaItems<ResenaItem>" "IList`1"
Libro o-> "ReposicionItems<ReposicionItem>" "IList`1"
Libro --> "SubastaItems<SubastaItem>" "IList`1"
@enduml
