@startuml
abstract class MetodoPago {
    + MetodoPago(id:int)
    + MetodoPago()
    + Id : int <<get>> <<set>>
}
class "IList`1"<T> {
}
MetodoPago o-> "Compras<Compra>" "IList`1"
MetodoPago o-> "Reposiciones<Reposicion>" "IList`1"
MetodoPago o-> "Subastas<Subasta>" "IList`1"
@enduml
