@startuml
class Reposicion {
    + Reposicion()
    + Reposicion(id:int, fechaReposicion:DateTime, precioTotal:decimal, comentario:string, admin:ApplicationUser, reposicionItems:IList<ReposicionItem>)
    + Id : int <<get>> <<set>>
    + PrecioTotal : decimal <<get>> <<set>>
    + Comentario : string? <<get>> <<set>>
}
class "IList`1"<T> {
}
Reposicion --> "FechaReposicion" DateTime
Reposicion o-> "ReposicionItems<ReposicionItem>" "IList`1"
Reposicion --> "Admin" ApplicationUser
@enduml
