@startuml
hide methods
!include ClassDiagram/Compra.puml
!include ClassDiagram/Libro.puml
!include ClassDiagram/ApplicationUser.puml
!include ClassDiagram/MetodoPago.puml
!include ClassDiagram/CompraItem.puml
!include ClassDiagram/Editorial.puml
!include ClassDiagram/Visa.puml
!include ClassDiagram/GooglePay.puml
!include ClassDiagram/Paypal.puml
!include ClassDiagram/Genero.puml
remove DateTime
remove *List*
@enduml